---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      deps:
        patterns:
          - "*"
    assignees:
      - lopopolo
    labels:
      - A-deps
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
    groups:
      deps:
        patterns:
          - "*"
    assignees:
      - lopopolo
    labels:
      - A-deps
