---
name: CI
"on":
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk
  schedule:
    - cron: "0 0 * * TUE"
concurrency:
  group: ci-${{ github.head_ref }}
jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Install Node.js toolchai
        uses: actions/setup-node@v4.0.2
        with:
          node-version: "lts/*"

      - name: Install toolchain
        run: npm ci

      - name: Build Webapp
        run: node build.mjs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847 # v3.9.2
        if: github.ref == 'refs/heads/trunk'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          cname: www.artichokeruby.org
          user_name: artichoke-ci
          user_email: ci@artichokeruby.org

  js:
    name: Lint JavaScript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Install Node.js toolchain
        uses: actions/setup-node@v4.0.2
        with:
          node-version: "lts/*"

      - name: Install toolchain
        run: npm ci

      - name: Lint with eslint
        run: npm run lint

  text:
    name: Lint and format text
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Install Node.js toolchain
        uses: actions/setup-node@v4.0.2
        with:
          node-version: "lts/*"

      - name: Install toolchain
        run: npm ci

      - name: Lint and check formatting with prettier
        run: npx prettier --check '**/*'

      - name: Lint YAML sources with yamllint
        run: |
          yamllint --version
          echo "Linting YAML sources with yamllint ..."
          yamllint --strict --format github .
          echo "OK"
